// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1200:Using directive should appear within a namespace declaration", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1208:Using directive for 'System.Linq' should appear before directive for 'Epam.Task01.Library.Entity'", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1633:The file header is missing or not located at the top of the file.", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.IBookLogic.AddBook(System.Collections.Generic.List{AbstractValidation.ValidationException},Epam.Task01.Library.Entity.Book)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.IBookLogic.CheckBookUniqueness(Epam.Task01.Library.Entity.Book)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.IBookLogic.GetBookById(System.Int32)~Epam.Task01.Library.Entity.Book")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.IBookLogic.GetBooksByPublishingCompany(System.String)~System.Collections.Generic.IEnumerable{System.Linq.IGrouping{System.String,Epam.Task01.Library.Entity.Book}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.ICommonLogic.DeleteLibraryItemById(System.Int32)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.ICommonLogic.GetLibraryItemsByTitle(System.String)~System.Collections.Generic.IEnumerable{Epam.Task01.Library.Entity.AbstractLibraryItem}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.ICommonLogic.GetLibraryItemsByYearOfPublishing~System.Collections.Generic.IEnumerable{System.Linq.IGrouping{System.Int32,Epam.Task01.Library.Entity.AbstractLibraryItem}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.INewspaperLogic.GetNewspaperItems~System.Collections.Generic.IEnumerable{Epam.Task01.Library.Entity.Newspaper}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.IPatentLogic.GetPatentItems~System.Collections.Generic.IEnumerable{Epam.Task01.Library.Entity.Patent}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.ISearchLogic.GetBooksAndPatentsByAuthor(Epam.Task01.Library.Entity.Author)~System.Collections.Generic.IEnumerable{Epam.Task01.Library.Entity.IWithAuthorProperty}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Epam.Task_01.Library.AbstactBLL.ISearchLogic.GetPatentsByAuthor(Epam.Task01.Library.Entity.Author)~System.Collections.Generic.IEnumerable{Epam.Task01.Library.Entity.Patent}")]